#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

PLUGIN_DIR="$CONFIG_DIR/plugins"
SCRIPT_DIR="$CONFIG_DIR/scripts"
ITEM_DIR="$CONFIG_DIR/items"
HELPER_DIR="$CONFIG_DIR/helper"

PADDING=4

bar_settings=(
	position=top
	height=40
	blur_radius=30
	color=0x000000ff
)

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.padding_left=$PADDING
  label.padding_right=$PADDING
)

sketchybar --bar "${bar_settings[@]}"
sketchybar --default "${default[@]}"

source "$ITEM_DIR/aerospace.sh"
sketchybar --add item chevron left \
		   --set chevron icon= icon.padding_left=15 label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

sketchybar --add item clock right \
           --set clock update_freq=1 script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=60 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change
source "$ITEM_DIR/music.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
